<a href="https://colab.research.google.com/github/Vasundharadevi-kanikicherla/Pandas-introduction-/blob/main/Introduction_To_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Numpy - Numeric Python
# Most powerful package - Library

# Numpy - Dimensions

# A - One Dimensional Array
# [A,B] || [A
#           B] - Two Dimensional Array - Row || Column

# Three Dimensional

# Array - Storing, Manipulating, Similar Data type

# Faster than any mathematical functions
# convenient compared to other packages
# Memory efficiency
# Support multi dimensional arrays

# speed(Numpy operations) > speed(Lists operations)
# size(Numpy operations) < size(Lists operations)

In [ ]:
# Install numpy _ pip3 install numpy // pip install numpy

In [ ]:
import numpy as np

In [ ]:
# Create a numpy array
# 1D array

arr1D = np.array([1,2,3,4,5])
print(arr1D)

[1 2 3 4 5]


In [ ]:
# Creating 2D array - Matrix
arr2D = np.array([
    [1,2,3],[4,5,6]
])
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Creating arrays with default values

# Creating matrix with all values of elements as '0'
allZeros = np.zeros((2,3))
print(allZeros)

# Creating matrix with all values of elements as '1'
allOnes = np.ones((2,3))
print(allOnes)

# Creating matrix with all values of elements as 'constant value- n ~ Fill value'
allConstant = np.full((2,3),6)
print(allConstant)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6 6 6]
 [6 6 6]]


In [ ]:
# Create an identity matrix - I - Square matrix

identity = np.eye(4)
print(identity)

# Identity Matrix - Aii = 1 && Aij = 0
# For all A Belongs to R M×N
# Aij

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Creating random Matrices

# between 0 and 1
rand1 = np.random.rand(3,3)
print(rand1)

# between a and b
rand2 = np.random.randint(10,20,(3,3))
print(rand2)

[[0.56383912 0.87271848 0.78911409]
 [0.04637806 0.42538917 0.72235625]
 [0.39531017 0.50040573 0.37117847]]
[[10 13 11]
 [16 16 15]
 [11 13 13]]


In [ ]:
# Array Properties

arr = np.array([[1,2,3,4],[2,3,4,5]])
print(arr)

# Shape or array
print(f'\nThe shape of the array is {arr.shape}')

# Size of array
print(f'The size of the array is {arr.size}')

# Datatype of array
print(f'The Data type of the array is {arr.dtype}')

# Dimensions of array
print(f'The Dimension of the array is {arr.ndim}')

[[1 2 3 4]
 [2 3 4 5]]

The shape of the array is (2, 4)
The size of the array is 8
The Data type of the array is int64
The Dimension of the array is 2


In [ ]:
# Indexing and Slicing

# Access the elements in 1D Array
arr = np.array([1,2,3,4])
print(arr)
print(arr[3])

# Slicing the elements
print(arr[0:3])
# Indexing and Slicing

# Slicing the elements
print(arr[0:3])

# Access the element in 2D Array
arr2 = np.array([[1,2,3],[2,3,4]])
print(arr2)
print(arr2[1,1])
print(arr2[0,:]) # first row with all columns
print(arr2[:,0]) # first Column with all rows

[1 2 3 4]
4
[1 2 3]
[1 2 3]
[[1 2 3]
 [2 3 4]]
3
[1 2 3]
[1 2]


In [ ]:
# L1 = []
# [L1.append(_) for _ in range(10)]

L1 = np.arange(10,-10,-1)

print(L1)

[10  9  8  7  6  5  4  3  2  1  0 -1 -2 -3 -4 -5 -6 -7 -8 -9]


In [ ]:
# Mathematical operations

a = np.array([1,2,3])
b = np.array([3,4,5])

print(f'The sum of a and b is {a+b}')
print(f'The diff of a and b is {a-b}')
print(f'The product of a and b is {a*b}')
print(f'The division of a and b is {a/b}')

The sum of a and b is [4 6 8]
The diff of a and b is [-2 -2 -2]
The product of a and b is [ 3  8 15]
The division of a and b is [0.33333333 0.5        0.6       ]


In [ ]:
print(b1)

[[1 2 3]
 [2 3 4]]


In [ ]:
print(b2)

[[5 6]
 [7 8]
 [1 3]]


In [ ]:
[
   [22,31],
   [35,48]
]

[[22, 31], [35, 48]]

In [ ]:
# Matrix multiplication
b1 = np.array([[1,2,3],[2,3,4]])
b2 = np.array([[5,6],[7,8],[1,3]])

# Dot product __ product=AB __ A m × n __ B n × p
c = np.dot(b1,b2)
print(c)

[[22 31]
 [35 48]]


In [ ]:
import numpy as np

In [ ]:
# Recap
arr = np.array(([1,2,3],[4,5,6]))

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
# Dot product - m × n || n × p
arr1 = np.random.randint(1,2,(1,2))

In [ ]:
arr1.shape

(1, 2)

In [ ]:
result = np.dot(arr1,arr)

In [ ]:
print(result)

[[5 7 9]]


In [ ]:
r1 = np.random.randint(10,20,(3,3))
print(r1)

[[15 13 10]
 [10 10 19]
 [14 15 12]]


In [ ]:
r2 = np.eye(3)
print(r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#r1.I
result2 = np.dot(r2,r1)

In [ ]:
print(result2)

[[15. 13. 10.]
 [10. 10. 19.]
 [14. 15. 12.]]


In [ ]:
#M . I = I . M = M

In [ ]:
 # A . B ! = B . A

In [ ]:
# Mathematical operations
# +-*/
t1 = np.random.randint(3,6,(3,3))
t2 = np.random.randint(3,6,(3,3))

In [ ]:
print(t1)
print(t2)

[[3 4 5]
 [5 5 5]
 [4 4 5]]
[[5 4 5]
 [4 4 3]
 [5 3 4]]


In [ ]:
t3 = t1 * t2

In [ ]:
print(t3)

[[15 16 25]
 [20 20 15]
 [20 12 20]]


In [ ]:
# Matrix multiplication
result = np.dot(arr1,arr)

In [ ]:
# Statistical operations
mean = t3.mean()
mode = t3.max()
median = np.median(t3)
std = np.std(t3)
var = np.var(t3)

In [ ]:
print(var)

13.654320987654323


In [ ]:
print(std)

3.6951753662924203


In [ ]:
std * std

13.654320987654323

In [ ]:
# Trigonometric functions
# Sin(x)
# Cos(x)
# Tan(x) - Sin(x) / Cos(x)
# Cosec - 1 / sin(x)
# Sec - 1 / cos(x)
# Cot - 1 / tan(x)
#
angles = np.array([0,15,30,45,60,75,90])

# Sin (array)

result = np.sin(np.radians(angles))
result1 = np.cos(np.radians(angles))
result2 = np.tan(np.radians(angles))

In [ ]:
print(result)
print(result1)
print(result2)

[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]


In [ ]:
arr = np.array([1,2,3,4,5,6])

# Reshape the array
reshapedarr = arr.reshape(3,2)

print(reshapedarr)

# Convert / Flatten any n dim array
flattenedarr = arr.flatten()

print(flattenedarr)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [ ]:
# Stacking the data
import numpy as np

arr1 = np.array([[1,2,3,4],[2,3,4,5]])
arr2 = np.array([10,20,30,40])

# Vertical Stacking
arr3 = np.vstack((arr1,arr2))
print(f"The shape of arr3 is {arr3.shape}")

# Horizontal Stacking
arr4 = np.hstack((arr1,arr2.reshape(2,2))) #Need to reshape to stack horizontally
print(f"The shape of arr4 is {arr4.shape}")
print(arr4)

The shape of arr3 is (3, 4)
The shape of arr4 is (2, 6)
[[ 1  2  3  4 10 20]
 [ 2  3  4  5 30 40]]


In [ ]:
# Filtering
arr = np.array([10,20,30,40,50,60,70,80])

farr = arr[arr > 40]

print(farr)

[50 60 70 80]
