<a href="https://colab.research.google.com/github/Vasundharadevi-kanikicherla/Pandas-introduction-/blob/main/Working_with_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Numpy - Numeric Python
# Most powerful package - Library

# Numpy - Dimension

# A - One Dimensional Array
# [A, B] || [ A
#             B ] - Two Dimensional Array- Row || Column

# Three Dimensional

# Array - Storing, Manipulating, Similar Data type

# Faster than any mathematical functions
# convenient compared to other packages
# Memory efficiency
# Support multi dimensional arrays

# speed(Numpy operations) > speed(Lists operations)
# size(Numpy operations) < size(Lists operations)

In [2]:
#Install numpy _ pip3 install  numpy // pip install numpy

In [3]:
import numpy as np

In [4]:
# Create a numpy array
# 1D array

arr1D = np.array([1,2,3,4,5])
print(arr1D)

[1 2 3 4 5]


In [5]:
# Creating 2D array - Matrix
arr2D = np.array([
    [1,2,3],[4,5,6]
])
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [6]:
# Creating arrays with default values

# Creating matrix with all values of elements as'0'
allZerors = np.zeros((2,3))
print(allZerors)

# Creating matrix with all values of elements as '1'
allOnes = np.ones((2,3))
print(allOnes)

# Creating matrix with all values of elements 'constant'
allConstant = np.full((2,3),6)
print(allConstant)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6 6 6]
 [6 6 6]]


In [8]:
# Create an identity matrix - I - Square matrix

identity = np.eye(4)
print(identity)

# Identity Matrix - Aii = 1 && Aij = 0
# For all A Belongs to R MxN
# Aij

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
# Creating random Matrices

# between 0 and 1
rand1 = np.random.rand(3,3)
print(rand1)

# between a and b
rand2 = np.random.randint(10,20,(3,3))
print(rand2)

[[0.97870579 0.90011064 0.41811273]
 [0.79414726 0.62550764 0.54821305]
 [0.52266576 0.44021232 0.05581628]]
[[19 12 19]
 [13 17 13]
 [17 11 12]]


In [9]:
# Array Properties

arr = np.array([[1,2,3,4],[2,3,4,5]])
print(arr)

# Shape or array
print(f'\nThe shape of the array is {arr.shape}')

# Size of array
print(f'The size  of the array is {arr.size}')

# Datatype of array
print(f'The Data type of the array is {arr.dtype}')

# Dimensions of array
print(f'The Dimension of the array is {arr.ndim}')

[[1 2 3 4]
 [2 3 4 5]]

The shape of the array is (2, 4)
The size  of the array is 8
The Data type of the array is int64
The Dimension of the array is 2


In [10]:
# Indexing and Slicing

# Access the elements in 1D Array

arr = np.array((1,2,3,4))
print(arr)
print(arr[3])

# Slicing the elements
print(arr[0:3])


# Access the elements in 2D array
arr2 = np.array([[1,2,3],[2,3,4]])
print(arr2)
print(arr2[1,1])
print(arr2[0,:]) # first row with all columns
print(arr2[:,0]) # first columns with all rows

[1 2 3 4]
4
[1 2 3]
[[1 2 3]
 [2 3 4]]
3
[1 2 3]
[1 2]


In [11]:
L1 = []
[L1.append(_) for _ in range(10)]

L1 = np.arange(10,-10,-1)

print(L1)

[10  9  8  7  6  5  4  3  2  1  0 -1 -2 -3 -4 -5 -6 -7 -8 -9]


In [12]:
# Mathematical operations

a = np.array([1,2,3])
b = np.array([3,4,5])

print(f'The sum of a and b is {a+b}')
print(f'The diff of a and b is {a-b}')
print(f'The product of a and b is {a*b}')
print(f'The division of a and b is {a/b}')

The sum of a and b is [4 6 8]
The diff of a and b is [-2 -2 -2]
The product of a and b is [ 3  8 15]
The division of a and b is [0.33333333 0.5        0.6       ]


In [13]:
# Matrix multiplication
b1 = np.array([[1,2,3],[2,3,4]])
b2 = np.array([[5,6],[7,8],[1,3]])

# Dot product __ product=AB __ A m × n __ B n × p
c = np.dot(b1,b2)
print(c)

[[22 31]
 [35 48]]


In [14]:
print(b1)

[[1 2 3]
 [2 3 4]]


In [15]:
print(b2)

[[5 6]
 [7 8]
 [1 3]]


In [16]:
[
   [22,31],
   [35,48]
]

[[22, 31], [35, 48]]